// Scene renderer for Claude's Fables — the storybook-anime visual upgrade.
//
// This is the warm, living picture-book heart of the app: layered painterly
// vignettes in a Studio-Ghibli / "Heidi, Girl of the Alps" register, with soft
// gradients, glowing light, atmospheric depth, and slow, calm CSS ambient
// motion. Everything still renders from the constrained scene-spec enums (see
// storybook-art.md + character-design.md), so the hot path stays fast: no SVG
// is generated by the model, and unknown enums fall back to the nearest known
// motif — NEVER crash, NEVER blank.
//
// All animation is CSS (transform/opacity only) via a scoped <style> injected
// inside the SVG. It is slow and gentle by design — this app lowers a heart
// rate, never raises it — and freezes calmly under prefers-reduced-motion.
//
// EXTENSIBILITY SEAMS (search "// + NEW"):
//   - new setting  = add one case in <Backdrop> + groundFor + a palette tweak
//   - new prop     = add one case in <PropLayer>           (// + NEW PROP)
//   - new animal   = add one helper + one case in <Body>   (// + NEW ANIMAL)
//   - new pose     = add one branch in poseInfo            (// + NEW POSE)
//   - new holding  = add one case in <HeldObject>          (// + NEW HOLDING)

import { useMemo } from "react";
import type {
  SceneSpec,
  Character,
  Setting,
  Prop,
  CharacterType,
  Pose,
  Holding,
  Mood,
} from "../types";

/* ================================================================== */
/* PALETTE — a soft painterly bedtime range. Gradients are allowed now */
/* (this is the upgrade); these are the anchor tones the ramps blend.  */
/* ================================================================== */
const C = {
  // night / dusk skies
  nightTop: "#141d3a",
  nightMid: "#243156",
  nightLow: "#3a4a78",
  // golden-hour sky
  dawnTop: "#6f5b8f",
  dawnMid: "#e6a16b",
  dawnLow: "#f6cf95",
  // light sources
  moon: "#F6ECCB",
  moonGlow: "#FBF4D8",
  sun: "#FFE9B0",
  sunGlow: "#FFD98A",
  star: "#FDF6E3",
  // land
  earth: "#3a2c1f",
  earthWarm: "#52402b",
  foliage: "#2e4a3a",
  foliageSoft: "#3c6048",
  hillFar: "#5c6f8e",
  hillMid: "#46603f",
  // characters (character-design.md house tones)
  crow: "#232a42",
  wing: "#2e3656",
  fox: "#C8863B",
  foxBelly: "#EAC18C",
  bird: "#85B7EB",
  birdWing: "#6FA3DC",
  rabbit: "#D8D6CC",
  rabbitDeep: "#BFBDB2",
  rabbitNose: "#ED93B1",
  child: "#E0A458",
  childDeep: "#C98A43",
  // accents
  eye: "#2A2233",
  eyeHi: "#FFFFFF",
  amber: "#E0A458",
  amberLight: "#F2C988",
  outline: "#C8863B",
  blush: "#F0A6A0",
  petal: "#F0C6D4",
  water: "#33507e",
  waterHi: "#7fa6cf",
} as const;

/* ================================================================== */
/* MOOD → time-of-day + lighting. Never anything scary.                */
/*   tender  = soft warm night                                         */
/*   hopeful = golden dawn warmth                                       */
/*   brave   = brighter warm day                                       */
/*   calm    = soft cool moonlight                                      */
/*   lonely  = a wistful blue hour (cooler/dimmer) — still safe+pretty  */
/* ================================================================== */
type Daylight = "night" | "dawn" | "day" | "moon" | "blue";

type MoodLight = {
  day: Daylight;
  glow: number; // 0..1.2 light-source intensity
  sky: [string, string, string]; // top, mid, low sky ramp
  light: string; // dominant warm/cool light colour
  vignette: number; // outer-darkness strength
  warmOverlay: string; // a final atmospheric wash
  warmOpacity: number;
};

function moodLight(mood: Mood | string): MoodLight {
  switch (mood) {
    case "hopeful":
      return {
        day: "dawn",
        glow: 1.1,
        sky: [C.dawnTop, C.dawnMid, C.dawnLow],
        light: C.sunGlow,
        vignette: 0.16,
        warmOverlay: "#FFCF8A",
        warmOpacity: 0.1,
      };
    case "brave":
      return {
        day: "day",
        glow: 1.2,
        sky: ["#5b6fa0", "#9ab0d0", "#f3d8a6"],
        light: C.sunGlow,
        vignette: 0.14,
        warmOverlay: "#FFD89A",
        warmOpacity: 0.08,
      };
    case "calm":
      return {
        day: "moon",
        glow: 0.95,
        sky: ["#172244", "#2a3a63", "#46618f"],
        light: C.moonGlow,
        vignette: 0.26,
        warmOverlay: "#9FB6E6",
        warmOpacity: 0.06,
      };
    case "lonely":
      // a wistful blue hour: cooler, dimmer, a touch bluer — but soft, pretty,
      // and never frightening.
      return {
        day: "blue",
        glow: 0.78,
        sky: ["#101a3a", "#1f2c54", "#33477a"],
        light: "#A9BBE6",
        vignette: 0.34,
        warmOverlay: "#3a4f86",
        warmOpacity: 0.12,
      };
    case "tender":
    default:
      // soft warm night (also the safe default for an unknown mood)
      return {
        day: "night",
        glow: 1,
        sky: [C.nightTop, C.nightMid, C.nightLow],
        light: C.moonGlow,
        vignette: 0.24,
        warmOverlay: "#E7B074",
        warmOpacity: 0.08,
      };
  }
}

/** Does this setting want a warm golden-hour read for warm moods? */
function isWarmDay(day: Daylight): boolean {
  return day === "dawn" || day === "day";
}

/* ================================================================== */
/* SHARED DEFS — gradients & filters. ids are namespaced per-scene (uid) */
/* so two mounted Scenes never collide.                                 */
/* ================================================================== */

function Defs({ uid, ml }: { uid: string; ml: MoodLight }) {
  const warm = isWarmDay(ml.day);
  return (
    <defs>
      {/* sky ramp */}
      <linearGradient id={`${uid}-sky`} x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor={ml.sky[0]} />
        <stop offset="55%" stopColor={ml.sky[1]} />
        <stop offset="100%" stopColor={ml.sky[2]} />
      </linearGradient>

      {/* a soft radial bloom around the light source */}
      <radialGradient id={`${uid}-bloom`} cx="50%" cy="50%" r="50%">
        <stop offset="0%" stopColor={ml.light} stopOpacity="0.55" />
        <stop offset="45%" stopColor={ml.light} stopOpacity="0.2" />
        <stop offset="100%" stopColor={ml.light} stopOpacity="0" />
      </radialGradient>

      {/* the moon/sun disc itself */}
      <radialGradient id={`${uid}-disc`} cx="42%" cy="40%" r="62%">
        <stop offset="0%" stopColor={warm ? C.sun : C.moonGlow} />
        <stop offset="100%" stopColor={warm ? C.sunGlow : C.moon} />
      </radialGradient>

      {/* warm-to-deep ground ramp */}
      <linearGradient id={`${uid}-ground`} x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor={warm ? "#6a5230" : C.earthWarm} />
        <stop offset="100%" stopColor={C.earth} />
      </linearGradient>

      {/* foliage ramp (lit top, deep base) */}
      <linearGradient id={`${uid}-leaf`} x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor={warm ? "#5e8a55" : C.foliageSoft} />
        <stop offset="100%" stopColor={C.foliage} />
      </linearGradient>

      {/* pond water ramp */}
      <linearGradient id={`${uid}-water`} x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor={ml.light} stopOpacity="0.35" />
        <stop offset="22%" stopColor={C.waterHi} stopOpacity="0.4" />
        <stop offset="100%" stopColor={C.water} />
      </linearGradient>

      {/* a vignette: transparent centre → soft dark corners */}
      <radialGradient id={`${uid}-vig`} cx="50%" cy="44%" r="72%">
        <stop offset="55%" stopColor="#000000" stopOpacity="0" />
        <stop offset="100%" stopColor="#000000" stopOpacity={ml.vignette} />
      </radialGradient>

      {/* a soft blur for glows (used sparingly) */}
      <filter id={`${uid}-soft`} x="-60%" y="-60%" width="220%" height="220%">
        <feGaussianBlur stdDeviation="3.4" />
      </filter>
      <filter id={`${uid}-soft2`} x="-80%" y="-80%" width="260%" height="260%">
        <feGaussianBlur stdDeviation="7" />
      </filter>

      {/* clip to the frame edge-to-edge; the container does any rounding */}
      <clipPath id={`${uid}-clip`}>
        <rect x="0" y="0" width="320" height="220" rx="0" />
      </clipPath>
    </defs>
  );
}

/* ================================================================== */
/* SCOPED ANIMATION STYLES — all CSS, slow & calm; freeze on reduce.    */
/* ================================================================== */

function Styles({ uid }: { uid: string }) {
  const css = `
  .${uid}-root * { transform-box: fill-box; }
  @keyframes ${uid}-drift {
    from { transform: translateX(-14px); }
    to   { transform: translateX(14px); }
  }
  @keyframes ${uid}-drift2 {
    from { transform: translateX(10px); }
    to   { transform: translateX(-10px); }
  }
  @keyframes ${uid}-breathe {
    0%,100% { transform: scale(1, 1); }
    50%     { transform: scale(1.018, 0.985); }
  }
  @keyframes ${uid}-bob {
    0%,100% { transform: translateY(0); }
    50%     { transform: translateY(-2.2px); }
  }
  @keyframes ${uid}-sway {
    0%,100% { transform: rotate(-2.2deg); }
    50%     { transform: rotate(2.2deg); }
  }
  @keyframes ${uid}-sway-soft {
    0%,100% { transform: rotate(-1.2deg); }
    50%     { transform: rotate(1.2deg); }
  }
  @keyframes ${uid}-twinkle {
    0%,100% { opacity: .35; transform: scale(.8); }
    50%     { opacity: 1;   transform: scale(1.15); }
  }
  @keyframes ${uid}-pulse {
    0%,100% { opacity: .55; transform: scale(1); }
    50%     { opacity: .9;  transform: scale(1.06); }
  }
  @keyframes ${uid}-float {
    0%   { opacity: 0;   transform: translate(0,0); }
    15%  { opacity: .9; }
    85%  { opacity: .7; }
    100% { opacity: 0;   transform: translate(14px,-26px); }
  }
  @keyframes ${uid}-mote {
    0%   { opacity: 0;   transform: translate(0,0); }
    20%  { opacity: .7; }
    100% { opacity: 0;   transform: translate(-10px,-34px); }
  }
  @keyframes ${uid}-shimmer {
    0%,100% { opacity: .25; transform: translateX(0); }
    50%     { opacity: .55; transform: translateX(8px); }
  }
  @keyframes ${uid}-blink {
    0%,93%,100% { transform: scaleY(1); }
    96%         { transform: scaleY(.1); }
  }
  @keyframes ${uid}-rays {
    0%,100% { opacity: .12; }
    50%     { opacity: .26; }
  }

  .${uid}-cloud   { animation: ${uid}-drift 26s ease-in-out infinite alternate; }
  .${uid}-cloud2  { animation: ${uid}-drift2 34s ease-in-out infinite alternate; }
  .${uid}-leaf    { animation: ${uid}-sway 7s ease-in-out infinite; transform-origin: bottom center; }
  .${uid}-leaf-b  { animation: ${uid}-sway-soft 9s ease-in-out infinite; transform-origin: bottom center; }
  .${uid}-grass   { animation: ${uid}-sway 5.5s ease-in-out infinite; transform-origin: bottom center; }
  .${uid}-star    { animation: ${uid}-twinkle 4s ease-in-out infinite; transform-origin: center; }
  .${uid}-glow    { animation: ${uid}-pulse 6s ease-in-out infinite; transform-origin: center; }
  .${uid}-firefly { animation: ${uid}-float 9s ease-in-out infinite; }
  .${uid}-mote    { animation: ${uid}-mote 12s linear infinite; }
  .${uid}-ripple  { animation: ${uid}-shimmer 6s ease-in-out infinite; }
  .${uid}-rays    { animation: ${uid}-rays 9s ease-in-out infinite; transform-origin: center; }
  .${uid}-petal   { animation: ${uid}-float 11s ease-in-out infinite; }

  .${uid}-char    { animation: ${uid}-breathe 5.5s ease-in-out infinite; transform-origin: bottom center; }
  .${uid}-char2   { animation: ${uid}-bob 6.5s ease-in-out infinite; }
  .${uid}-eye     { animation: ${uid}-blink 7s ease-in-out infinite; transform-origin: center; }

  @media (prefers-reduced-motion: reduce) {
    .${uid}-root * { animation: none !important; }
  }
  `;
  return <style>{css}</style>;
}

/* ================================================================== */
/* LIGHT SOURCE (moon / sun) with bloom, halo & optional god-rays.      */
/* ================================================================== */

function LightSource({
  uid,
  ml,
  x = 252,
  y = 52,
  rays = false,
}: {
  uid: string;
  ml: MoodLight;
  x?: number;
  y?: number;
  rays?: boolean;
}) {
  const warm = isWarmDay(ml.day);
  const r = warm ? 30 : 24;
  return (
    <g>
      {/* big soft bloom */}
      <circle
        className={`${uid}-glow`}
        cx={x}
        cy={y}
        r={92}
        fill={`url(#${uid}-bloom)`}
        opacity={ml.glow}
      />
      {/* god-rays (only where it fits — open sky / golden hour) */}
      {rays && (
        <g
          className={`${uid}-rays`}
          filter={`url(#${uid}-soft2)`}
          style={{ mixBlendMode: "screen" } as React.CSSProperties}
        >
          {[-34, -18, 0, 18, 34].map((a) => (
            <polygon
              key={a}
              points={`${x},${y} ${x - 14},260 ${x + 14},260`}
              fill={ml.light}
              opacity={0.5}
              transform={`rotate(${a} ${x} ${y})`}
            />
          ))}
        </g>
      )}
      {/* halo */}
      <circle cx={x} cy={y} r={r + 12} fill={ml.light} opacity={0.18 * ml.glow} filter={`url(#${uid}-soft)`} />
      {/* the disc */}
      <circle cx={x} cy={y} r={r} fill={`url(#${uid}-disc)`} />
      {/* a soft crescent shadow only for the cool night/moon reads */}
      {!warm && ml.day !== "day" && (
        <circle cx={x - 9} cy={y - 5} r={r - 4} fill={ml.sky[0]} opacity={0.32} />
      )}
      {/* a faint surface texture so the moon isn't a flat dot */}
      {!warm && (
        <g fill="#000" opacity="0.05">
          <circle cx={x + 6} cy={y + 7} r="3.5" />
          <circle cx={x - 4} cy={y + 9} r="2" />
          <circle cx={x + 11} cy={y - 3} r="2.4" />
        </g>
      )}
    </g>
  );
}

/* ================================================================== */
/* SKY EXTRAS — stars, drifting clouds, dust motes (atmosphere).        */
/* ================================================================== */

function Stars({ uid, ml }: { uid: string; ml: MoodLight }) {
  // hand-placed twinkles that avoid the upper-right light source.
  const pts: Array<[number, number, number, number]> = [
    [34, 28, 1.9, 0],
    [70, 56, 1.4, 1.2],
    [108, 22, 2.1, 0.6],
    [150, 44, 1.5, 2.1],
    [40, 92, 1.5, 1.6],
    [188, 30, 1.4, 0.9],
    [96, 80, 1.2, 2.6],
    [300, 110, 1.6, 1.1],
    [284, 150, 1.3, 0.4],
    [132, 64, 1.1, 3.1],
  ];
  const dim = ml.day === "day" ? 0.25 : ml.day === "dawn" ? 0.5 : 1;
  return (
    <g fill={C.star}>
      {pts.map(([x, y, r, delay], i) => (
        <circle
          key={i}
          className={`${uid}-star`}
          cx={x}
          cy={y}
          r={r}
          opacity={0.9 * dim}
          style={{ animationDelay: `${delay}s` }}
        />
      ))}
    </g>
  );
}

function Clouds({ uid, ml }: { uid: string; ml: MoodLight }) {
  const warm = isWarmDay(ml.day);
  const fill = warm ? "#fbe2bb" : "#33437a";
  const op = warm ? 0.7 : 0.55;
  const cloud = (cx: number, cy: number, s: number) => (
    <g transform={`translate(${cx} ${cy}) scale(${s})`}>
      <ellipse cx="0" cy="0" rx="30" ry="12" fill={fill} opacity={op} />
      <ellipse cx="-18" cy="3" rx="18" ry="9" fill={fill} opacity={op} />
      <ellipse cx="20" cy="3" rx="20" ry="10" fill={fill} opacity={op} />
      <ellipse cx="2" cy="-6" rx="16" ry="9" fill={fill} opacity={op * 0.9} />
    </g>
  );
  return (
    <g filter={`url(#${uid}-soft)`}>
      <g className={`${uid}-cloud`}>{cloud(74, 60, 0.85)}</g>
      <g className={`${uid}-cloud2`}>{cloud(210, 92, 1)}</g>
    </g>
  );
}

function DustMotes({ uid, ml }: { uid: string; ml: MoodLight }) {
  // a few slow drifting light particles — air made visible.
  const motes: Array<[number, number, number, number]> = [
    [60, 150, 2, 0],
    [130, 120, 1.6, 3],
    [205, 160, 2.2, 6],
    [255, 130, 1.5, 1.5],
    [95, 175, 1.8, 4.5],
    [170, 145, 1.4, 7.5],
  ];
  return (
    <g fill={ml.light}>
      {motes.map(([x, y, r, d], i) => (
        <circle
          key={i}
          className={`${uid}-mote`}
          cx={x}
          cy={y}
          r={r}
          opacity={0.5}
          style={{ animationDelay: `${d}s` }}
        />
      ))}
    </g>
  );
}

/* ================================================================== */
/* PROPS                                                               */
/* ================================================================== */

function Lantern({ uid }: { uid: string }) {
  // a small hanging lantern with a real warm glow.
  return (
    <g transform="translate(50 44)">
      <line x1="0" y1="-16" x2="0" y2="4" stroke={C.outline} strokeWidth="1.6" />
      <circle className={`${uid}-glow`} cx="0" cy="24" r="26" fill={C.amber} opacity="0.22" filter={`url(#${uid}-soft)`} />
      <circle cx="0" cy="24" r="14" fill={C.amberLight} opacity="0.4" />
      <rect x="-9" y="10" width="18" height="24" rx="7" fill={C.amberLight} />
      <rect x="-9" y="10" width="18" height="24" rx="7" fill="none" stroke={C.outline} strokeWidth="1.6" />
      <rect x="-6" y="4" width="12" height="7" rx="3" fill={C.outline} />
      <ellipse cx="-3" cy="20" rx="2.4" ry="4" fill={C.sunGlow} opacity="0.8" />
    </g>
  );
}

function Fireflies({ uid }: { uid: string }) {
  const pts: Array<[number, number, number]> = [
    [72, 150, 0],
    [118, 126, 1.6],
    [156, 158, 3.1],
    [210, 132, 0.8],
    [246, 162, 2.3],
    [92, 176, 4.2],
  ];
  return (
    <g>
      {pts.map(([x, y, d], i) => (
        <g key={i} className={`${uid}-firefly`} style={{ animationDelay: `${d}s` }}>
          <circle cx={x} cy={y} r="7" fill={C.amberLight} opacity="0.22" filter={`url(#${uid}-soft)`} />
          <circle cx={x} cy={y} r="2.3" fill={C.sunGlow} />
        </g>
      ))}
    </g>
  );
}

function FallenLeaves({ uid, ground }: { uid: string; ground: number }) {
  const y = ground + 16;
  const leaves: Array<[number, number, number]> = [
    [54, y - 2, -18],
    [118, y + 4, 14],
    [186, y, -6],
    [248, y + 6, 24],
    [292, y - 4, -16],
  ];
  return (
    <g>
      {leaves.map(([x, ly, rot], i) => (
        <g key={i} className={`${uid}-leaf-b`} transform={`translate(${x} ${ly}) rotate(${rot})`} style={{ animationDelay: `${i * 0.7}s` }}>
          <path d="M0 0 q9 -5 0 -10 q-9 5 0 10 z" fill={C.outline} opacity="0.92" />
          <path d="M0 0 q9 -5 0 -10" fill="none" stroke={C.amberLight} strokeWidth="0.7" opacity="0.6" />
        </g>
      ))}
    </g>
  );
}

function SingleFlower({ uid, ground }: { uid: string; ground: number }) {
  const baseY = ground + 14;
  return (
    <g className={`${uid}-grass`} transform={`translate(64 ${baseY})`} style={{ animationDelay: "0.4s" }}>
      <path d="M0 0 q-2 -12 0 -22" fill="none" stroke={C.foliageSoft} strokeWidth="2.4" strokeLinecap="round" />
      <path d="M-1 -10 q-7 -2 -10 -7 q7 -1 11 4 z" fill={C.foliageSoft} />
      <g transform="translate(0 -26)">
        {[0, 72, 144, 216, 288].map((a) => (
          <ellipse key={a} cx="0" cy="-6" rx="3.6" ry="5.4" fill={C.petal} transform={`rotate(${a})`} />
        ))}
        <circle cx="0" cy="0" r="3.2" fill={C.amber} />
        <circle cx="-1" cy="-1" r="1.2" fill={C.amberLight} />
      </g>
    </g>
  );
}

function PropLayer({
  prop,
  uid,
  ground,
}: {
  prop: Prop | string;
  uid: string;
  ground: number;
}) {
  switch (prop) {
    case "lantern":
      return <Lantern uid={uid} />;
    case "fireflies":
      return <Fireflies uid={uid} />;
    case "fallen_leaves":
      return <FallenLeaves uid={uid} ground={ground} />;
    case "single_flower":
      return <SingleFlower uid={uid} ground={ground} />;
    // moon & stars are handled in the sky layer; nothing to draw here.
    case "moon":
    case "stars":
      return null;
    // + NEW PROP: add a case here returning one helper.
    default:
      // unknown prop → draw nothing rather than crash (closest = absence)
      return null;
  }
}

/* ================================================================== */
/* SETTINGS (backdrops) — layered parallax: sky already drawn; here we  */
/* add distant hills/treeline, midground, and the foreground floor.     */
/* ================================================================== */

function Hill(props: { d: string; fill: string; opacity?: number }) {
  return <path d={props.d} fill={props.fill} opacity={props.opacity ?? 1} />;
}

function Backdrop({
  setting,
  uid,
  ml,
}: {
  setting: Setting | string;
  uid: string;
  ml: MoodLight;
}) {
  const warm = isWarmDay(ml.day);
  const ground = `url(#${uid}-ground)`;
  const leaf = `url(#${uid}-leaf)`;

  switch (setting) {
    /* ----- a thick branch high in a tree at night ------------------ */
    case "night_branch":
      return (
        <g>
          {/* distant misty treeline */}
          <Hill d="M0 130 q60 -26 120 -6 q70 22 200 -10 L320 220 L0 220 Z" fill={C.hillFar} opacity={0.5} />
          {/* canopy masses, swaying gently */}
          <g className={`${uid}-leaf-b`}>
            <ellipse cx="44" cy="96" rx="58" ry="40" fill={leaf} opacity="0.85" />
            <ellipse cx="286" cy="78" rx="64" ry="44" fill={leaf} opacity="0.85" />
          </g>
          {/* the branch the characters perch on */}
          <path d="M-12 176 Q150 152 332 180" fill="none" stroke={ground} strokeWidth="16" strokeLinecap="round" />
          <path d="M-12 176 Q150 152 332 180" fill="none" stroke="#23190f" strokeWidth="16" strokeLinecap="round" opacity="0.25" />
          {/* a small offshoot + leaf cluster, swaying */}
          <path d="M84 168 q12 -24 34 -30" fill="none" stroke={ground} strokeWidth="7" strokeLinecap="round" />
          <g className={`${uid}-leaf`} style={{ animationDelay: "1.2s" }}>
            <ellipse cx="120" cy="132" rx="20" ry="12" fill={leaf} />
            <ellipse cx="100" cy="140" rx="14" ry="9" fill={leaf} />
          </g>
        </g>
      );

    /* ----- a soft clearing on the forest floor --------------------- */
    case "forest_floor":
      return (
        <g>
          {/* far hills, paler & bluer with distance */}
          <Hill d="M0 124 q80 -34 170 -8 q90 24 150 -6 L320 220 L0 220 Z" fill={warm ? "#7d8aa0" : C.hillFar} opacity={0.55} />
          <Hill d="M0 150 q90 -22 200 0 q70 14 120 -6 L320 220 L0 220 Z" fill={warm ? C.hillMid : "#3c5340"} opacity={0.85} />
          {/* back tree trunks + canopy */}
          <rect x="24" y="86" width="15" height="92" rx="6" fill={C.earthWarm} opacity="0.85" />
          <rect x="282" y="74" width="17" height="104" rx="6" fill={C.earthWarm} opacity="0.85" />
          <g className={`${uid}-leaf-b`}>
            <ellipse cx="31" cy="80" rx="40" ry="30" fill={leaf} opacity="0.9" />
            <ellipse cx="290" cy="66" rx="46" ry="34" fill={leaf} opacity="0.9" />
          </g>
          {/* foreground floor */}
          <path d="M0 176 Q160 166 320 176 L320 220 L0 220 Z" fill={ground} />
          <path d="M0 176 Q160 166 320 176" fill="none" stroke={warm ? "#7da06a" : C.foliageSoft} strokeWidth="3" opacity="0.5" />
          {/* swaying grass tufts */}
          {[26, 70, 250, 300].map((gx, i) => (
            <g key={gx} className={`${uid}-grass`} transform={`translate(${gx} 184)`} style={{ animationDelay: `${i * 0.6}s` }}>
              {[-4, 0, 4].map((dx, j) => (
                <path key={j} d={`M${dx} 0 q${dx * 0.5} -10 ${dx * 0.3} -16`} fill="none" stroke={warm ? "#82a86c" : C.foliageSoft} strokeWidth="2" strokeLinecap="round" />
              ))}
            </g>
          ))}
        </g>
      );

    /* ----- a woven nest, cradle-warm -------------------------------- */
    case "cozy_nest":
      return (
        <g>
          {/* soft far foliage haze */}
          <Hill d="M0 110 q80 -10 160 0 q80 10 160 0 L320 220 L0 220 Z" fill={leaf} opacity={0.4} />
          {/* supporting branch */}
          <path d="M-10 196 Q160 184 330 198" fill="none" stroke={ground} strokeWidth="12" strokeLinecap="round" />
          {/* the woven nest bowl */}
          <ellipse cx="160" cy="190" rx="126" ry="44" fill={C.earthWarm} />
          <ellipse cx="160" cy="184" rx="104" ry="32" fill={C.earth} />
          <ellipse cx="160" cy="178" rx="86" ry="22" fill="#5a4530" />
          {/* woven strands along the rim */}
          {[-92, -58, -22, 16, 52, 90].map((dx, i) => (
            <path
              key={i}
              d={`M${160 + dx} 200 q${dx > 0 ? 12 : -12} -26 ${dx > 0 ? 20 : -20} -34`}
              fill="none"
              stroke={C.outline}
              strokeWidth="2.6"
              strokeLinecap="round"
              opacity="0.7"
            />
          ))}
          {/* a couple of soft down feathers in the bowl */}
          <ellipse cx="120" cy="180" rx="6" ry="3" fill={C.amberLight} opacity="0.5" transform="rotate(-20 120 180)" />
          <ellipse cx="206" cy="184" rx="6" ry="3" fill={C.amberLight} opacity="0.5" transform="rotate(16 206 184)" />
        </g>
      );

    /* ----- the still edge of a pond --------------------------------- */
    case "pond_edge":
      return (
        <g>
          {/* far hills + reflected sky */}
          <Hill d="M0 132 q90 -28 180 -4 q80 20 140 -8 L320 220 L0 220 Z" fill={warm ? "#7d8aa0" : C.hillFar} opacity={0.5} />
          {/* grassy bank coming in from the left */}
          <path d="M0 166 Q70 156 150 168 Q120 182 70 186 L0 192 Z" fill={leaf} />
          {/* the water */}
          <path d="M0 182 H320 V220 H0 Z" fill={`url(#${uid}-water)`} />
          {/* light reflection band */}
          <rect className={`${uid}-ripple`} x="150" y="188" width="150" height="5" rx="3" fill={ml.light} opacity="0.3" filter={`url(#${uid}-soft)`} />
          {/* gentle ripple lines */}
          {[196, 206, 214].map((ry, i) => (
            <path
              key={i}
              className={`${uid}-ripple`}
              d={`M150 ${ry} q26 -4 52 0 t52 0 t52 0`}
              fill="none"
              stroke={C.waterHi}
              strokeWidth="1.4"
              opacity="0.3"
              style={{ animationDelay: `${i * 1.3}s` }}
            />
          ))}
          {/* reeds, swaying */}
          {[140, 152, 164].map((rx, i) => (
            <path key={rx} className={`${uid}-grass`} d={`M${rx} 184 q${i % 2 ? 4 : -4} -16 ${i % 2 ? 2 : -2} -28`} fill="none" stroke={C.foliageSoft} strokeWidth="2.6" strokeLinecap="round" style={{ animationDelay: `${i * 0.5}s` }} />
          ))}
          {/* a lily pad */}
          <ellipse cx="250" cy="200" rx="16" ry="6" fill={C.foliageSoft} opacity="0.85" />
        </g>
      );

    /* ----- a cozy windowsill looking out on the night --------------- */
    case "bedroom_window":
      return (
        <g>
          {/* warm room wall framing the window */}
          <rect x="0" y="0" width="320" height="220" fill="#5a3f2e" opacity="0.0" />
          {/* the night view inside the frame (its own little sky) */}
          <rect x="42" y="20" width="236" height="156" rx="10" fill={`url(#${uid}-sky)`} />
          {/* distant rooftops/hills seen through the glass */}
          <path d="M42 150 q50 -16 110 -2 q70 14 126 -6 L278 176 L42 176 Z" fill={C.hillFar} opacity="0.55" />
          {/* a tiny far cottage glow */}
          <rect x="120" y="138" width="10" height="10" rx="2" fill={C.amberLight} opacity="0.7" />
          <rect x="200" y="146" width="8" height="8" rx="2" fill={C.amberLight} opacity="0.6" />
          {/* warm frame */}
          <rect x="40" y="18" width="240" height="160" rx="12" fill="none" stroke="#7a5230" strokeWidth="7" />
          <rect x="40" y="18" width="240" height="160" rx="12" fill="none" stroke={C.outline} strokeWidth="2.5" opacity="0.6" />
          <line x1="160" y1="20" x2="160" y2="176" stroke="#7a5230" strokeWidth="5" />
          <line x1="42" y1="98" x2="278" y2="98" stroke="#7a5230" strokeWidth="5" />
          {/* a soft curtain edge */}
          <path d="M40 18 q-10 80 4 160" fill="#6a4a33" opacity="0.5" />
          {/* the windowsill the character rests on */}
          <rect x="26" y="176" width="268" height="16" rx="6" fill={`url(#${uid}-ground)`} />
          <rect x="18" y="192" width="284" height="28" fill={C.earthWarm} opacity="0.85" />
          <rect x="26" y="176" width="268" height="3" rx="2" fill={C.amberLight} opacity="0.4" />
        </g>
      );

    /* ----- wide open sky, lots of air ------------------------------- */
    case "open_sky":
      return (
        <g>
          {/* far hills at the very bottom, hazy */}
          <Hill d="M0 188 q80 -16 170 -2 q90 12 150 -4 L320 220 L0 220 Z" fill={warm ? "#8e99ad" : C.hillFar} opacity={0.5} />
          {/* a soft cloud bank for characters that "perch" on air */}
          <g filter={`url(#${uid}-soft)`}>
            <g className={`${uid}-cloud2`}>
              <ellipse cx="160" cy="166" rx="86" ry="22" fill={warm ? "#fce4bd" : "#3a4d84"} opacity="0.75" />
              <ellipse cx="110" cy="172" rx="42" ry="16" fill={warm ? "#fce4bd" : "#3a4d84"} opacity="0.75" />
              <ellipse cx="214" cy="172" rx="48" ry="18" fill={warm ? "#fce4bd" : "#3a4d84"} opacity="0.75" />
            </g>
          </g>
        </g>
      );

    // + NEW SETTING: add a case here returning the backdrop group.
    default:
      // unknown setting → night_branch (the canonical first scene)
      return <Backdrop setting="night_branch" uid={uid} ml={ml} />;
  }
}

/** A baseline y for where a character's "feet" rest, per setting. */
function groundFor(setting: Setting | string): number {
  switch (setting) {
    case "night_branch":
      return 176;
    case "cozy_nest":
      return 180;
    case "bedroom_window":
      return 176;
    case "pond_edge":
      return 178;
    case "open_sky":
      return 162;
    case "forest_floor":
    default:
      return 180;
  }
}

/* ================================================================== */
/* HELD OBJECTS                                                         */
/* ================================================================== */

function HeldObject({ holding, uid }: { holding: Holding | string; uid: string }) {
  switch (holding) {
    case "bread":
      // a warm little loaf with a soft glow
      return (
        <g>
          <ellipse cx="0" cy="0" rx="11" ry="7.5" fill={C.amberLight} />
          <ellipse cx="0" cy="-1.5" rx="11" ry="7.5" fill={C.amber} opacity="0.5" />
          <ellipse cx="0" cy="0" rx="11" ry="7.5" fill="none" stroke={C.outline} strokeWidth="1.3" />
          <path d="M-5 -4 l1.5 -2 M0 -5 l0 -2 M5 -4 l-1.5 -2" stroke={C.outline} strokeWidth="1" strokeLinecap="round" />
          <ellipse cx="-3" cy="-2" rx="3" ry="1.6" fill={C.sunGlow} opacity="0.7" />
        </g>
      );
    case "lantern":
      return (
        <g>
          <circle className={`${uid}-glow`} cx="0" cy="0" r="15" fill={C.amber} opacity="0.28" filter={`url(#${uid}-soft)`} />
          <rect x="-6" y="-7" width="12" height="16" rx="4" fill={C.amberLight} />
          <rect x="-6" y="-7" width="12" height="16" rx="4" fill="none" stroke={C.outline} strokeWidth="1.2" />
          <rect x="-4" y="-11" width="8" height="4" rx="2" fill={C.outline} />
          <ellipse cx="-1.5" cy="1" rx="2" ry="3.4" fill={C.sunGlow} opacity="0.85" />
        </g>
      );
    case "flower":
      return (
        <g>
          {[0, 72, 144, 216, 288].map((a) => (
            <ellipse key={a} cx="0" cy="-5.5" rx="3.4" ry="5" fill={C.petal} transform={`rotate(${a})`} />
          ))}
          <circle cx="0" cy="0" r="2.8" fill={C.amber} />
          <circle cx="-0.8" cy="-0.8" r="1" fill={C.amberLight} />
        </g>
      );
    // + NEW HOLDING: add a case here.
    case null:
    default:
      return null;
  }
}

/* ================================================================== */
/* CHARACTERS                                                          */
/* ================================================================== */
//
// One construction grammar shared by every animal (character-design.md):
//   soft body ellipse + an oversized round head sitting high & slightly
//   forward + a single cream eye-dot (now with a tiny highlight + a blink) +
//   a soft cheek blush + an amber face accent + short rounded limbs + a gentle
//   smile. A soft rim-light and a faint contact shadow give it form.
// Poses transform the SAME base — they never redraw the body.
//
// Local coordinate convention: origin (0,0) = where the feet meet the ground;
// the body sits above in -y; the character faces RIGHT by default (flip for
// pairs).

type PoseInfo = {
  headTilt: number;
  legSpread: number;
  legOffset: number;
  limbUp: boolean;
  offer: boolean;
  curl: boolean;
};

function poseInfo(pose: Pose | string): PoseInfo {
  switch (pose) {
    case "looking_up":
      return { headTilt: -16, legSpread: 6, legOffset: 0, limbUp: false, offer: false, curl: false };
    case "offering":
      return { headTilt: -4, legSpread: 6, legOffset: 0, limbUp: false, offer: true, curl: false };
    case "curled":
      return { headTilt: 6, legSpread: 5, legOffset: 0, limbUp: false, offer: false, curl: true };
    case "walking":
      return { headTilt: 0, legSpread: 8, legOffset: 6, limbUp: false, offer: false, curl: false };
    case "reaching":
      return { headTilt: -10, legSpread: 6, legOffset: 0, limbUp: true, offer: false, curl: false };
    case "perched":
      return { headTilt: 0, legSpread: 6, legOffset: 0, limbUp: false, offer: false, curl: false };
    // + NEW POSE: add a branch here returning the transform knobs.
    default:
      return { headTilt: 0, legSpread: 6, legOffset: 0, limbUp: false, offer: false, curl: false };
  }
}

function heldSpot(p: PoseInfo): { x: number; y: number } {
  if (p.curl) return { x: 4, y: -10 };
  if (p.offer) return { x: 24, y: -16 };
  return { x: 17, y: -11 };
}

/** The shared expressive face: cream eye with a highlight that blinks, a soft
 *  blush, and a gentle smile. cx/cy = head centre in the head-group's space. */
function Face({
  uid,
  eyeX,
  eyeY,
  blushX,
  smileX,
  smileY,
  dark = false,
}: {
  uid: string;
  eyeX: number;
  eyeY: number;
  blushX: number;
  smileX: number;
  smileY: number;
  dark?: boolean;
}) {
  return (
    <g>
      {/* soft cheek blush */}
      <ellipse cx={blushX} cy={eyeY + 5} rx="3" ry="2" fill={C.blush} opacity="0.5" />
      {/* eye — blinks occasionally */}
      <g className={`${uid}-eye`}>
        <ellipse cx={eyeX} cy={eyeY} rx="2.9" ry="3.2" fill={C.eye} />
        <circle cx={eyeX + 1} cy={eyeY - 1.2} r="1" fill={C.eyeHi} />
      </g>
      {/* gentle smile */}
      <path d={`M${smileX - 3} ${smileY} q3 3 6 0`} fill="none" stroke={dark ? "#0d1226" : C.eye} strokeWidth="1.3" strokeLinecap="round" opacity="0.7" />
    </g>
  );
}

/** Faint contact shadow under the feet. */
function ContactShadow() {
  return <ellipse cx="0" cy="2" rx="20" ry="5" fill="#000" opacity="0.16" filter="" />;
}

/* ---- crow -------------------------------------------------------- */
function Crow({ p, uid }: { p: PoseInfo; uid: string }) {
  const bodyDx = p.curl ? -3 : 0;
  return (
    <g>
      <ContactShadow />
      {/* legs */}
      <line x1={-p.legSpread + p.legOffset} y1="-2" x2={-p.legSpread} y2="-14" stroke={C.crow} strokeWidth="2.6" strokeLinecap="round" />
      <line x1={p.legSpread - p.legOffset} y1="-2" x2={p.legSpread} y2="-14" stroke={C.crow} strokeWidth="2.6" strokeLinecap="round" />
      {/* body */}
      <ellipse cx={bodyDx} cy={p.curl ? -22 : -24} rx={p.curl ? 24 : 22} ry={p.curl ? 18 : 16} fill={C.crow} />
      {/* rim light on the upper-right */}
      <path d={`M${bodyDx + 4} -36 q16 4 16 16`} fill="none" stroke={C.wing} strokeWidth="3" strokeLinecap="round" opacity="0.8" />
      {/* wing — extends forward when offering / lifts when reaching */}
      {p.offer ? (
        <path d={`M${bodyDx + 4} -26 q18 -4 30 6 q-12 8 -28 2 z`} fill={C.wing} />
      ) : p.limbUp ? (
        <path d={`M${bodyDx + 2} -30 q14 -16 8 -32 q-12 6 -16 26 z`} fill={C.wing} />
      ) : (
        <ellipse cx={bodyDx + 5} cy={p.curl ? -22 : -24} rx="13" ry={p.curl ? 14 : 11} fill={C.wing} />
      )}
      {/* head group (tilts for looking_up) */}
      <g transform={`translate(${bodyDx - 12} -38) rotate(${p.headTilt})`}>
        <circle cx="0" cy="0" r="13" fill={C.crow} />
        <ellipse cx="3" cy="-5" rx="6" ry="4" fill={C.wing} opacity="0.6" />
        <path d="M-12 0 l-13 3 l13 4 z" fill={C.amber} />
        <Face uid={uid} eyeX={-3} eyeY={-2} blushX={-7} smileX={-9} smileY={4} />
      </g>
    </g>
  );
}

/* ---- fox --------------------------------------------------------- */
// + NEW ANIMAL: copy this pattern (one helper) and add a case in <Body>.
function Fox({ p, uid }: { p: PoseInfo; uid: string }) {
  const bodyDx = p.curl ? -3 : 0;
  return (
    <g>
      <ContactShadow />
      {/* curved tail with amber tip */}
      <path d={`M${bodyDx + 16} -22 q26 -2 30 -26 q-14 4 -22 14 q-6 6 -8 12 z`} fill={C.fox} />
      <path d={`M${bodyDx + 40} -46 q8 0 6 12 q-10 -2 -14 -6 z`} fill={C.foxBelly} />
      {/* legs */}
      <line x1={-p.legSpread + p.legOffset} y1="-2" x2={-p.legSpread} y2="-14" stroke={C.fox} strokeWidth="3.2" strokeLinecap="round" />
      <line x1={p.legSpread - p.legOffset} y1="-2" x2={p.legSpread} y2="-14" stroke={C.fox} strokeWidth="3.2" strokeLinecap="round" />
      {/* body + belly */}
      <ellipse cx={bodyDx} cy={p.curl ? -22 : -24} rx={p.curl ? 24 : 22} ry={p.curl ? 18 : 16} fill={C.fox} />
      <ellipse cx={bodyDx + 2} cy={p.curl ? -16 : -18} rx="13" ry="9" fill={C.foxBelly} />
      {/* rim light */}
      <path d={`M${bodyDx - 6} -36 q-10 4 -12 14`} fill="none" stroke={C.foxBelly} strokeWidth="2.6" strokeLinecap="round" opacity="0.7" />
      {/* forward paw when offering / raised when reaching */}
      {p.offer && <ellipse cx={bodyDx + 22} cy="-14" rx="7" ry="5" fill={C.fox} />}
      {p.limbUp && <line x1={bodyDx + 6} y1="-30" x2={bodyDx + 12} y2="-50" stroke={C.fox} strokeWidth="4.2" strokeLinecap="round" />}
      {/* head group */}
      <g transform={`translate(${bodyDx - 12} -38) rotate(${p.headTilt})`}>
        {/* ears */}
        <path d="M-9 -9 l-3 -13 l10 6 z" fill={C.fox} />
        <path d="M5 -10 l3 -13 l-10 7 z" fill={C.fox} />
        <path d="M-7 -10 l-1 -7 l5 4 z" fill={C.crow} opacity="0.45" />
        <circle cx="0" cy="0" r="13" fill={C.fox} />
        <ellipse cx="3" cy="-5" rx="6" ry="4" fill={C.foxBelly} opacity="0.5" />
        {/* muzzle */}
        <path d="M-12 1 l-10 3 l10 4 z" fill={C.foxBelly} />
        <circle cx="-21" cy="4" r="2.2" fill={C.crow} />
        <Face uid={uid} eyeX={-3} eyeY={-2} blushX={-8} smileX={-12} smileY={5} />
      </g>
    </g>
  );
}

/* ---- little bird ------------------------------------------------- */
function LittleBird({ p, uid }: { p: PoseInfo; uid: string }) {
  const bodyDx = p.curl ? -2 : 0;
  return (
    <g transform="scale(0.74)">
      <ContactShadow />
      <line x1={-p.legSpread + p.legOffset} y1="-2" x2={-p.legSpread} y2="-12" stroke={C.outline} strokeWidth="2.6" strokeLinecap="round" />
      <line x1={p.legSpread - p.legOffset} y1="-2" x2={p.legSpread} y2="-12" stroke={C.outline} strokeWidth="2.6" strokeLinecap="round" />
      <ellipse cx={bodyDx} cy={p.curl ? -20 : -22} rx={p.curl ? 22 : 21} ry={p.curl ? 18 : 16} fill={C.bird} />
      <ellipse cx={bodyDx + 2} cy={p.curl ? -16 : -17} rx="11" ry="8" fill="#A8CEF1" />
      <path d={`M${bodyDx + 4} -34 q14 4 14 14`} fill="none" stroke="#A8CEF1" strokeWidth="2.4" strokeLinecap="round" opacity="0.7" />
      {p.offer ? (
        <path d={`M${bodyDx + 4} -24 q16 -2 24 8 q-12 6 -22 0 z`} fill={C.birdWing} />
      ) : p.limbUp ? (
        <path d={`M${bodyDx} -28 q12 -14 6 -28 q-10 6 -12 22 z`} fill={C.birdWing} />
      ) : (
        <ellipse cx={bodyDx + 4} cy={p.curl ? -20 : -22} rx="11" ry={p.curl ? 13 : 10} fill={C.birdWing} />
      )}
      <g transform={`translate(${bodyDx - 11} -34) rotate(${p.headTilt})`}>
        <circle cx="0" cy="0" r="13" fill={C.bird} />
        <ellipse cx="3" cy="-5" rx="6" ry="4" fill="#A8CEF1" opacity="0.7" />
        <path d="M-12 0 l-10 2 l10 3 z" fill={C.amber} />
        <Face uid={uid} eyeX={-3} eyeY={-2} blushX={-7} smileX={-9} smileY={4} />
      </g>
    </g>
  );
}

/* ---- rabbit ------------------------------------------------------ */
function Rabbit({ p, uid }: { p: PoseInfo; uid: string }) {
  const bodyDx = p.curl ? -3 : 0;
  return (
    <g>
      <ContactShadow />
      {/* tiny round tail */}
      <circle cx={bodyDx + 18} cy="-18" r="6.5" fill="#F0EEE6" />
      <line x1={-p.legSpread + p.legOffset} y1="-2" x2={-p.legSpread} y2="-12" stroke={C.rabbitDeep} strokeWidth="3.6" strokeLinecap="round" />
      <line x1={p.legSpread - p.legOffset} y1="-2" x2={p.legSpread} y2="-12" stroke={C.rabbitDeep} strokeWidth="3.6" strokeLinecap="round" />
      <ellipse cx={bodyDx} cy={p.curl ? -22 : -24} rx={p.curl ? 24 : 21} ry={p.curl ? 18 : 17} fill={C.rabbit} />
      <ellipse cx={bodyDx + 1} cy={p.curl ? -17 : -19} rx="11" ry="8" fill="#EFEDE6" />
      {p.offer && <ellipse cx={bodyDx + 20} cy="-14" rx="7" ry="5" fill={C.rabbit} />}
      {p.limbUp && <line x1={bodyDx + 4} y1="-30" x2={bodyDx + 8} y2="-50" stroke={C.rabbit} strokeWidth="5" strokeLinecap="round" />}
      <g transform={`translate(${bodyDx - 11} -40) rotate(${p.headTilt})`}>
        {/* two long ears, gently swaying with the body */}
        <ellipse cx="-4" cy="-22" rx="4.5" ry="15" fill={C.rabbit} transform="rotate(-10)" />
        <ellipse cx="6" cy="-22" rx="4.5" ry="15" fill={C.rabbit} transform="rotate(10)" />
        <ellipse cx="-4" cy="-22" rx="2" ry="10" fill={C.rabbitNose} opacity="0.55" transform="rotate(-10)" />
        <ellipse cx="6" cy="-22" rx="2" ry="10" fill={C.rabbitNose} opacity="0.55" transform="rotate(10)" />
        <circle cx="0" cy="0" r="13" fill={C.rabbit} />
        <ellipse cx="3" cy="-5" rx="6" ry="4" fill="#EFEDE6" opacity="0.8" />
        <circle cx="-9" cy="3" r="2.2" fill={C.rabbitNose} />
        <Face uid={uid} eyeX={-3} eyeY={-2} blushX={-7} smileX={-9} smileY={5} />
      </g>
    </g>
  );
}

/* ---- child (deliberately abstract / non-specific) --------------- */
function Child({ p, uid }: { p: PoseInfo; uid: string }) {
  const bodyDx = p.curl ? -3 : 0;
  return (
    <g>
      <ContactShadow />
      {/* legs */}
      <line x1={-p.legSpread + p.legOffset} y1="-2" x2={-p.legSpread + 1} y2="-16" stroke={C.childDeep} strokeWidth="4.4" strokeLinecap="round" />
      <line x1={p.legSpread - p.legOffset} y1="-2" x2={p.legSpread - 1} y2="-16" stroke={C.childDeep} strokeWidth="4.4" strokeLinecap="round" />
      {/* soft rounded body (little nightgown) */}
      <path d={`M${bodyDx - 13} ${p.curl ? -36 : -40} q13 -6 26 0 l3 ${p.curl ? 24 : 28} q-16 6 -32 0 z`} fill={C.child} />
      <path d={`M${bodyDx - 11} ${p.curl ? -36 : -40} q11 -5 22 0`} fill="none" stroke={C.amberLight} strokeWidth="2" opacity="0.6" />
      {/* an arm — extended for offering / raised for reaching */}
      {p.offer && <line x1={bodyDx + 8} y1="-30" x2={bodyDx + 24} y2="-30" stroke={C.child} strokeWidth="4.2" strokeLinecap="round" />}
      {p.limbUp && <line x1={bodyDx + 8} y1="-34" x2={bodyDx + 16} y2="-54" stroke={C.child} strokeWidth="4.2" strokeLinecap="round" />}
      {/* head — round, soft hair cap, gentle face */}
      <g transform={`translate(${bodyDx} -52) rotate(${p.headTilt * 0.5})`}>
        <circle cx="0" cy="0" r="13" fill="#F2D2A4" />
        {/* soft hair */}
        <path d="M-13 -2 q0 -16 13 -16 q13 0 13 16 q-6 -7 -13 -7 q-7 0 -13 7 z" fill={C.childDeep} />
        {/* two eyes + a smile (kept abstract — never a specific child) */}
        <g className={`${uid}-eye`}>
          <ellipse cx="-4.5" cy="0" rx="1.8" ry="2.2" fill={C.eye} />
          <ellipse cx="4.5" cy="0" rx="1.8" ry="2.2" fill={C.eye} />
        </g>
        <ellipse cx="-7" cy="4" rx="2.6" ry="1.7" fill={C.blush} opacity="0.55" />
        <ellipse cx="7" cy="4" rx="2.6" ry="1.7" fill={C.blush} opacity="0.55" />
        <path d="M-3.5 5 q3.5 4 7 0" fill="none" stroke={C.eye} strokeWidth="1.4" strokeLinecap="round" opacity="0.75" />
      </g>
    </g>
  );
}

/** Dispatch a character type → its hand-built helper. */
function Body({ type, p, uid }: { type: CharacterType | string; p: PoseInfo; uid: string }) {
  switch (type) {
    case "crow":
      return <Crow p={p} uid={uid} />;
    case "fox":
      return <Fox p={p} uid={uid} />;
    case "little_bird":
      return <LittleBird p={p} uid={uid} />;
    case "rabbit":
      return <Rabbit p={p} uid={uid} />;
    case "child":
      return <Child p={p} uid={uid} />;
    // + NEW ANIMAL: add a case here pointing at a new helper above.
    default:
      // unknown type → crow (the canonical hero)
      return <Crow p={p} uid={uid} />;
  }
}

/* ================================================================== */
/* CHARACTER PLACEMENT                                                 */
/* ================================================================== */

function PlacedCharacter({
  c,
  x,
  ground,
  faceLeft,
  uid,
  idx,
}: {
  c: Character;
  x: number;
  ground: number;
  faceLeft?: boolean;
  uid: string;
  idx: number;
}) {
  const scale = (c.size === "big" ? 1.5 : 1) * 1.08;
  const p = poseInfo(c.pose);
  const flip = faceLeft ? -1 : 1;
  const spot = heldSpot(p);
  return (
    // outer group: a gentle idle bob (different phase per character)
    <g className={`${uid}-char2`} style={{ animationDelay: `${idx * 1.1}s` }}>
      {/* a soft warm rim-light wash behind the character for depth */}
      <g transform={`translate(${x} ${ground})`}>
        {/* breathing group */}
        <g className={`${uid}-char`} style={{ animationDelay: `${idx * 0.9}s` }}>
          <g transform={`scale(${flip * scale} ${scale})`}>
            <Body type={c.type} p={p} uid={uid} />
            {c.holding != null && (
              <g transform={`translate(${spot.x} ${spot.y}) scale(${flip} 1)`}>
                <HeldObject holding={c.holding} uid={uid} />
              </g>
            )}
          </g>
        </g>
      </g>
    </g>
  );
}

/* ================================================================== */
/* SCENE                                                              */
/* ================================================================== */

let sceneCounter = 0;

export default function Scene({ spec, className }: { spec: SceneSpec; className?: string }) {
  // a stable, unique id per mounted Scene so gradient/filter/animation ids
  // and @keyframes names never collide when two Scenes render at once.
  const uid = useMemo(() => `sc${(sceneCounter++).toString(36)}${Math.floor(Math.random() * 1e4).toString(36)}`, []);

  // Defensive defaults — a malformed spec must still render something warm.
  const setting: Setting | string = spec?.setting ?? "night_branch";
  const props: Array<Prop | string> = Array.isArray(spec?.props) ? spec.props : [];
  const characters: Character[] = Array.isArray(spec?.characters) ? spec.characters : [];
  const mood: Mood | string = spec?.mood ?? "tender";
  const ml = moodLight(mood);
  const ground = groundFor(setting);

  const hasMoon = props.includes("moon");
  const hasStars = props.includes("stars");
  // open sky & golden-hour scenes earn god-rays; tuck the light up-left there
  // for the sky, up-right otherwise.
  const wantRays = setting === "open_sky" || isWarmDay(ml.day);
  const lightX = setting === "open_sky" ? 232 : 252;
  const lightY = setting === "open_sky" ? 56 : 52;

  // Layout: one character centred; a pair faces each other so they don't
  // overlap (a big one offering toward a small one looking up reads naturally).
  const positions = characters.length <= 1 ? [160] : [108, 214];
  const facing = characters.length <= 1 ? [false] : [false, true];

  return (
    <svg
      className={`${uid}-root ${className ?? ""}`.trim()}
      viewBox="0 0 320 220"
      preserveAspectRatio="xMidYMid slice"
      role="img"
      aria-label={`A storybook scene set in ${typeof setting === "string" ? setting.replace(/_/g, " ") : "a quiet place"}`}
      style={{ display: "block", width: "100%", height: "100%" }}
    >
      <Defs uid={uid} ml={ml} />
      <Styles uid={uid} />

      {/* everything clipped to the rounded card */}
      <g clipPath={`url(#${uid}-clip)`}>
        {/* graded sky */}
        <rect x="0" y="0" width="320" height="220" fill={`url(#${uid}-sky)`} />

        {/* atmospheric clouds high in the sky (behind everything) */}
        <Clouds uid={uid} ml={ml} />

        {/* stars (default-on for cool/night reads even without the prop, so the
            sky never feels empty; the moon only when asked) */}
        {(hasStars || ml.day === "night" || ml.day === "blue" || ml.day === "moon") && (
          <Stars uid={uid} ml={ml} />
        )}

        {/* the light source: explicit moon, or an ambient sun for warm days */}
        {(hasMoon || isWarmDay(ml.day)) && (
          <LightSource uid={uid} ml={ml} x={lightX} y={lightY} rays={wantRays} />
        )}

        {/* setting backdrop (hills → midground → foreground floor) */}
        <Backdrop setting={setting} uid={uid} ml={ml} />

        {/* floating dust motes in the air for depth & magic */}
        <DustMotes uid={uid} ml={ml} />

        {/* ground-level + ambient props (drawn on top of the floor) */}
        {props
          .filter((pr) => pr !== "moon" && pr !== "stars")
          .map((pr, i) => (
            <PropLayer key={`${pr}-${i}`} prop={pr} uid={uid} ground={ground} />
          ))}

        {/* characters */}
        {characters.slice(0, 2).map((c, i) => (
          <PlacedCharacter
            key={i}
            c={c}
            x={positions[i] ?? 160}
            ground={ground}
            faceLeft={facing[i]}
            uid={uid}
            idx={i}
          />
        ))}

        {/* atmospheric warm/cool wash (never anything scary) */}
        <rect
          x="0"
          y="0"
          width="320"
          height="220"
          fill={ml.warmOverlay}
          opacity={ml.warmOpacity}
          pointerEvents="none"
          style={{ mixBlendMode: "soft-light" } as React.CSSProperties}
        />

        {/* soft vignette frames the cozy little world */}
        <rect x="0" y="0" width="320" height="220" fill={`url(#${uid}-vig)`} pointerEvents="none" />
      </g>
    </svg>
  );
}
