// Bundle the Vercel serverless function into ONE self-contained file at
// api/fable.js. esbuild inlines the entire src import graph (engine, validator,
// sanitizer, demos JSON, generated prompt strings) so the deployed function has
// no cross-directory relative imports — which Vercel's per-file TS transpile
// does not resolve. @anthropic-ai/sdk is left external and resolved from
// node_modules at runtime (it is a production dependency).
//
// Runs as part of `npm run build` (after gen:prompts + vite build), and the
// committed api/fable.js is what Vercel serves.

import { build } from "esbuild";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

await build({
  entryPoints: [join(root, "src/server/vercelEntry.ts")],
  outfile: join(root, "api/fable.js"),
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node18",
  external: ["@anthropic-ai/sdk"],
  legalComments: "none",
  logLevel: "warning",
  banner: {
    js: "// AUTO-GENERATED by scripts/build-api.mjs from src/server/vercelEntry.ts — do not edit by hand.",
  },
});

console.log("build-api: wrote api/fable.js (self-contained CJS bundle)");
