// Bundle each Vercel serverless function into ONE self-contained file under
// /api. esbuild inlines the whole src import graph so the deployed function has
// no cross-directory relative imports — which Vercel's per-file TS transpile
// does not resolve. Heavy/dual-published deps are left external and resolved
// from node_modules at runtime; ESM-only deps (livekit-server-sdk) are bundled
// so a CommonJS function can use them.
//
// Runs as part of `npm run build` (after gen:prompts + vite build); the
// committed api/*.js files are what Vercel serves.

import { build } from "esbuild";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const banner = (src) => ({
  js: `// AUTO-GENERATED by scripts/build-api.mjs from ${src} — do not edit by hand.`,
});

const common = {
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node18",
  legalComments: "none",
  logLevel: "warning",
};

// /api/fable — the Opus fable engine. @anthropic-ai/sdk stays external (large,
// dual-published) and is resolved from node_modules on Vercel.
await build({
  ...common,
  entryPoints: [join(root, "src/server/vercelEntry.ts")],
  outfile: join(root, "api/fable.js"),
  external: ["@anthropic-ai/sdk"],
  banner: banner("src/server/vercelEntry.ts"),
});

// /api/token — mints a LiveKit room token. livekit-server-sdk + @livekit/protocol
// are ESM-only, so we BUNDLE them (don't external) so the CJS function can use them.
await build({
  ...common,
  entryPoints: [join(root, "src/server/tokenEntry.ts")],
  outfile: join(root, "api/token.js"),
  external: [],
  banner: banner("src/server/tokenEntry.ts"),
});

console.log("build-api: wrote api/fable.js + api/token.js (self-contained CJS bundles)");
