// Single source of truth for the runtime prompts.
//
// CLAUDE.md requires that /src/prompts/*.md be copied VERBATIM from the matching
// .claude/skills/*/SKILL.md bodies, so build-time and runtime share one source.
// This script does exactly that, and ALSO emits src/prompts.generated.ts so the
// serverless function can import the prompt text as plain string constants —
// bundle-safe, no fs reads or raw-loader needed on Vercel.
//
// Run automatically via the `prebuild` / `predev` npm hooks; also `npm run gen:prompts`.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

// skill folder name -> exported const name in prompts.generated.ts
const SKILLS = {
  "fable-author": "fableAuthorPrompt",
  "storybook-art": "storybookArtPrompt",
  "child-guardian": "childGuardianPrompt",
  "tender-ui": "tenderUiPrompt",
  "character-design": "characterDesignPrompt",
};

/** Strip the YAML frontmatter block, returning just the markdown body. */
function stripFrontmatter(text) {
  if (!text.startsWith("---")) return text.trim();
  const end = text.indexOf("\n---", 3);
  if (end === -1) return text.trim();
  const after = text.indexOf("\n", end + 1);
  return text.slice(after + 1).trim();
}

const promptsDir = join(root, "src", "prompts");
mkdirSync(promptsDir, { recursive: true });

const entries = [];
for (const [slug, constName] of Object.entries(SKILLS)) {
  const skillPath = join(root, ".claude", "skills", slug, "SKILL.md");
  const raw = readFileSync(skillPath, "utf8");
  const body = stripFrontmatter(raw);

  // 1) verbatim body -> /src/prompts/<slug>.md  (CLAUDE.md file-tree requirement)
  writeFileSync(join(promptsDir, `${slug}.md`), body + "\n", "utf8");

  // 2) collect for the generated TS module
  entries.push({ slug, constName, body });
}

const banner =
  "// AUTO-GENERATED by scripts/gen-prompts.mjs — DO NOT EDIT BY HAND.\n" +
  "// Source of truth: .claude/skills/*/SKILL.md (also copied to src/prompts/*.md).\n" +
  "// Regenerate with: npm run gen:prompts\n\n";

const consts = entries
  .map((e) => `export const ${e.constName} = ${JSON.stringify(e.body)};`)
  .join("\n\n");

const map =
  "\nexport const PROMPTS = {\n" +
  entries.map((e) => `  ${JSON.stringify(e.slug)}: ${e.constName},`).join("\n") +
  "\n} as const;\n";

writeFileSync(
  join(root, "src", "prompts.generated.ts"),
  banner + consts + "\n" + map,
  "utf8",
);

console.log(
  `gen-prompts: wrote ${entries.length} prompt bodies to src/prompts/*.md and src/prompts.generated.ts`,
);
